# Generated by Django 5.2.7 on 2026-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keysmith", "0002_remove_token_hint_and_add_created_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="prefix",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
