# Generated by Django 5.2.7 on 2026-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keysmith", "0003_alter_token_prefix"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tokenauditlog",
            index=models.Index(fields=["ip_address"], name="keysmith_to_ip_addr_b9ff68_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenauditlog",
            index=models.Index(fields=["status_code"], name="keysmith_to_status__3e40dd_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenauditlog",
            index=models.Index(
                fields=["action", "created_at"], name="keysmith_to_action_fbcd66_idx"
            ),
        ),
    ]
