# Generated by Django 5.2.7 on 2026-06-10 12:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("keysmith", "0005_alter_token_created_by_alter_token_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("key", models.CharField(max_length=256, unique=True)),
                ("prefix", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                ("purged", models.BooleanField(default=False)),
                (
                    "custom_field",
                    models.CharField(default="default_value", max_length=50),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scopes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Django permissions associated with this token",
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tests_custom_token",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["key"], name="tests_custo_key_41d6f9_idx"),
                    models.Index(
                        fields=["expires_at"], name="tests_custo_expires_2fdcd6_idx"
                    ),
                    models.Index(
                        fields=["revoked"], name="tests_custo_revoked_e27235_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomTokenAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auth_success", "Authentication Success"),
                            ("auth_failed", "Authentication Failed"),
                            ("created", "Token Created"),
                            ("revoked", "Token Revoked"),
                            ("rotated", "Token Rotated"),
                        ],
                        max_length=64,
                    ),
                ),
                ("path", models.TextField(help_text="Request path (without domain)")),
                ("method", models.CharField(help_text="HTTP method", max_length=10)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        help_text="HTTP response status code"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (errors, reason, actor, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_log_field",
                    models.CharField(default="default_log_value", max_length=50),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_logs",
                        to="keysmith.token",
                    ),
                ),
            ],
            options={
                "db_table": "tests_custom_token_audit_log",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["token"], name="tests_custo_token_i_2ee873_idx"
                    ),
                    models.Index(
                        fields=["action"], name="tests_custo_action_57498f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tests_custo_created_6a4e01_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="tests_custo_ip_addr_60d286_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="tests_custo_status__ef765b_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="tests_custo_action_0273c4_idx",
                    ),
                ],
            },
        ),
    ]
